version: 2
jobs:
  build:
    working_directory: ~/react-shopping-cart
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: test the dependencies
          command: npm run test
      - run:
          name: build static code
          command: npm run build
      - run: 
          name: install aws cli
          command: sudo apt-get install awscli -y
      - run:
          name: deploy on s3
          command: aws --region eu-west-1 s3 sync dist s3://cloudfrisk-web-app/ --delete
