version: 2
jobs:
  build:
    working_directory: ~/react-shopping-cart
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: test the dependencies
          command: npm run test
      - run:
          name: build static code
          command: npm run build && cd build && ls
      - run: 
          name: install aws cli
          command: sudo apt-get install awscli -y && aws s3 ls
      - run:
          name: deploy on s3
          command: aws --region eu-west-1 s3 sync build/ s3://shopping-web-app/ --delete
