version: 2
jobs:
  build:
    machine: true
    working_directory: ~/react-shopping-cart
    steps:
      - add_ssh_keys:
          fingerprints:
            - "75:1c:bf:ca:cc:24:12:7b:e4:d4:53:f3:32:25:11:53"

      - checkout
      # - run:
      #     name: build and push docker image
      #     command: |
      #             sudo docker build -t gulzamank/shopping-app:latest .
      #             echo $dockerhubpass |sudo docker login -u $username -p $dockerhubpass
      #             sudo docker push gulzamank/shopping-app:latest
      - run:
          name: ssh into ec2 machine and run docker
          command: |
                  sudo ssh -o StrictHostKeyChecking=no ubuntu@52.211.205.70
                  sudo docker pull gulzamank/shopping-app:latest
                  sudo docker run -p 8080:8080 gulzamank/shopping-app
      - store_artifacts:
          path: test-reports
          destination: test-reports
