version: 2
jobs:
  build:
    machine: true
    working_directory: ~/react-shopping-cart
    steps:
      - checkout
      - run:
          name: Build and push Django Docker image
          command: |
                  sudo docker build -t gulzamank/shopping-app:latest .
                  echo $dockerhubpass |sudo docker login -u $username -p $dockerhubpass
                  sudo docker push gulzamank/shopping-app:latest
      - store_artifacts:
          path: test-reports
          destination: test-reports
